version: '3.8'

services:
   postgres:
      image: postgres
      env_file:
         - ./.env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
         - '15432:5432'
      networks:
         - database

networks:
   database:
